services:
    dh.artis_simple_product_variant_hotfix_plugin.form.extension.product_type:
        class: DH\ArtisSimpleProductVariantOverwriteHotfixPlugin\Form\ProductTypeExtension
        tags:
            - { name: form.type_extension }
